# Generated by Django 2.2.9 on 2021-07-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acao_movimentacao',
            new_name='AcaoMovimentacao',
        ),
    ]
