# Generated by Django 2.2.9 on 2021-07-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_auto_20210725_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aplicacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Aplicacao')),
            ],
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='status',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.DeleteModel(
            name='StatusMovimentacao',
        ),
        migrations.AddField(
            model_name='retirada',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Movimentacao'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Movimentacao'),
        ),
    ]
